# Node docker image on which this would be run
image: node:latest

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   NODE_ENV: 'test'

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - node_modules
      - build

services:
   - mongo

stages:
  - install
  - build
  - test
  - staging

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm  ci

Build_api:
  stage: build
  before_script:
     - npm run clean
  script:
    - npm run build

test_api:
  stage: test
  script:
    - npm run test:coveralls

deploy_staging:
  image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine # This image has Node.js and Ruby
  only:
    - develop
  stage: staging
  before_script:
    # Install Node.js and Ruby dependencies
    - npm install netlify-cli -g
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    # Deploy to Netlify
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
    - echo "Deployed to Netlify staging server"
    # Deploy to Heroku
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_STAGING --api-key=$HEROKU_API_KEY
    - echo "Deployed to Heroku staging server"

