language: node_js

node_js:
  - "16.20.2"

cache:
  directories:
    - node_modules
    - "$CI_PROJECT_DIR/.npm"
    - build

services:
  - mongodb

env:
  global:
    - MONGO_DB=mongodb://localhost/test

branches:
  only:
    - main

install:
  - npm ci

before_script:
  - npm run clean
  - npm run build

script:
  - npm run test:coveralls

after_success:
  - npm run coverage
